### ISSUE TITLE
Issue on boot-up

### ISSUE THREAD

**Issue by GraysonCAdams** [Urkaz/UrkazMoonTools#3]
I have Bloodmoon installed and was testing this out... but I get the following error:

```
java.lang.NoSuchMethodError: net.minecraft.block.Block.setTranslationKey(Ljava/lang/String;)Lnet/minecraft/block/Block;
	at com.urkaz.moontools.init.EventSuscriber$RegistrationHandler.registerBlocks(EventSuscriber.java:31)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_802_RegistrationHandler_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Looks like it is stemming from this mod, based on the 2nd line of the stack trace.

**Comment by GraysonCAdams** [comment]
Looking at how previous mod creators have resolved this, could this be due to you using a different version of Forge than this is claimed to be compatible with?

https://github.com/copygirl/WearableBackpacks/issues/11#issuecomment-280937514

**Comment by GraysonCAdams** [comment]
I am on Forge 14.23.5.2854

**Comment by Urkaz** [comment]
Thanks for the report.
I'm trying to figure out what's happening, but I'm completely lost. I'm using Forge 14.23.5.2854 for my tests (with and without mods), and even the mod is built for 14.23.5.2847 it works correctly.

I've rebuilt the mod with the forge dependency to make sure the mod loads after forge, but I don't know if this will fix the problem.

@GraysonCAdams Download this and see if the problem persists, if yes, please upload the full log and the crash file and I will continue to investigate this.
[UrkazMoonTools-1.12.2-1.7.jar.zip](https://github.com/Urkaz/UrkazMoonTools/files/6176512/UrkazMoonTools-1.12.2-1.7.jar.zip)
(The .jar of the mod is inside the zip, I had to compress it to make it available as an attachment).

**Comment by GraysonCAdams** [comment]
Hey, that did seem to allow the game to launch, actually.

I can see it loaded in my mods. Will test in single player real quick.

**Comment by GraysonCAdams** [comment]
Works great with this change!

**Comment by Urkaz** [comment]
Okay, perfect then!
Thanks for your time testing it and for pointing out the fix!

I'm not sure why this never happened on previous versions, but 🤷‍♂️ haha

I'll upload the jar to Curseforge in the following minutes. It will be the same as the one attached here, so you won't need to download the update again.
